### ISSUE TITLE
Consider more standard behavior for logging directory

### ISSUE THREAD

**Issue by jlperla** [torfjelde/TuringCallbacks.jl#10]
Given experience with https://pytorch.org/docs/stable/tensorboard.html  and see https://pytorch.org/docs/master/_modules/torch/utils/tensorboard/writer.html#SummaryWriter

I suggest following the pytorch/tensorflow approach above which I think is

```julia
function TensorBoardCallback(comment::String = "", log_dir::String = nothing, args...; kwargs...)
    if isnothing(log_dir)
        directory =  "runs/$(Dates.format(now(), dateformat"ud_H-M-S"))-$(gethostname())$(comment)"
    else
        directory = log_dir
    end

    lg = TBLogger(directory, min_level=Logging.Info; step_increment=0)

    return TensorBoardCallback(lg, args...; kwargs...)
end
```
which I believe mimics the constructor behavior for teh pytorch summarywriter:
```python
        if not log_dir:
            import socket
            from datetime import datetime
            current_time = datetime.now().strftime('%b%d_%H-%M-%S')
            log_dir = os.path.join(
                'runs', current_time + '_' + socket.gethostname() + comment)
```

One benefit of this is that all tensorboard docs will use the `runs` as the basic directory to look inside, so this would pick them all up and make it easy to distinguish the experiments.

**Comment by torfjelde** [comment]
This sounds like a great idea! Though I'll go with `Dates.format(now(), dateformat"Y-m-d_H-M-S")`.
